# Generated by Django 4.1.5 on 2023-01-26 13:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harga',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 26, 20, 33, 14, 801973)),
        ),
    ]
